### ISSUE TITLE
Does your code use GPU?

### ISSUE THREAD

**Issue by Coronal-Halo** [javrtg/DAC#1]
It seems your code does not use GPU, I wonder why that is? Can I expect a speed improvement by using GPU in the feature detection phase?

**Comment by javrtg** [comment]
Hi @Coronal-Halo yes, GPU can be used when running the code, and it should indeed provide speed improvements.

I wonder if you are asking this because in some parts of the code, cpu was forced, e.g. [here](https://github.com/javrtg/DAC/blob/11660b338b928375c9346a5f3063624eb4536c67/detectors/keynet/keynet_utils.py#L77-L79). 

Originally I had the code like this because I used to ran out of memory when using my local GPU, and I accidently left this unchanged. It should be fixed now with latest commit.

In any case, thank you for pointing this out! Let me know if this helps.

**Comment by Coronal-Halo** [comment]
I see, thank you for the prompt reply and fix!
